# Generated by Django 6.0.2 on 2026-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_data_science', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'Case study', 'verbose_name_plural': 'Case studies'},
        ),
        migrations.AddField(
            model_name='casestudy',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
